# 工作流名称
name: Sync-Images
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 触发工作流
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image 
      run: |
        while read -r line; do
        
            if [[ -z "$line" || "$line" == \#* ]]; then
              continue
            fi

            if [[ "$line"== "*/*/*" ]]; then
                repo=$(echo $line |awk -F / '{print $1"/"$2"/"}')
                image=$(echo $line |awk -F / '{print $3}')
                echo "$repo $image"
            fi

      
        done < docker-images.txt 
